[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"  # or "dist" or "out", depending on your project
  node_version = "18"

[context.production.environment]
  NODE_VERSION = "18"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"  # Avoid unnecessary strict CI behaviors

[[plugins]]
  package = "@netlify/plugin-cache-core"
